{% set name = "ipyvolume" %}
{% set version = "0.5.2" %}
{% set sha256 = "19cbdeea2d889cd1bb70f7b82f814833ad0b3d115c8171d7b7860851d8fbbd26" %}


package:
  name: ipyvolume
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyvolume/ipyvolume-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - traittypes
    - traitlets
    - ipywidgets >=7.4
    # We constraints pillow version on Windows
    # as it seems to trigger some DLL errors. See
    # here for more informations:
    #   - https://github.com/conda-forge/ipyvolume-feedstock/pull/28
    #   - https://github.com/maartenbreddels/ipyvolume/issues/208#issuecomment-442877181
    #   - https://github.com/conda-forge/pillow-feedstock/issues/45
    - pillow >5.2  # [win]
    - pillow  # [not win]
    - scipy
    - numpy
    - scikit-image >=0.13
    - requests
    - ipywebrtc >=0.4
    - pythreejs >=1.0

test:
  imports:
    - ipyvolume

about:
  home: https://github.com/maartenbreddels/ipyvolume
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'IPython widget for rendering 3d volumes in the Jupter notebook'
  doc_url: https://ipyvolume.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipyvolume

extra:
  recipe-maintainers:
    - maartenbreddels
