{% set name = "ipyvolume" %}
{% set version = "0.6.0a6" %}
{% set sha256 = "1a71c681dd39b514db966c4812bbbd1347ce082ee7a7bcc53f494e0546bf37ff" %}


package:
  name: ipyvolume
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyvolume/ipyvolume-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - traittypes
    - traitlets
    - ipywidgets >=7.4
    # We need constraints pillow version on Windows, but due to noarch will require it for all os
    # as it seems to trigger some DLL errors. See
    # here for more informations:
    #   - https://github.com/conda-forge/ipyvolume-feedstock/pull/28
    #   - https://github.com/maartenbreddels/ipyvolume/issues/208#issuecomment-442877181
    #   - https://github.com/conda-forge/pillow-feedstock/issues/45
    - pillow >5.2
    - scipy
    - numpy
    - scikit-image >=0.13
    - requests
    - ipywebrtc >=0.4
    - pythreejs >=1.0
    - bqplot >=0.12

test:
  imports:
    - ipyvolume

about:
  home: https://github.com/maartenbreddels/ipyvolume
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'IPython widget for rendering 3d volumes in the Jupter notebook'
  doc_url: https://ipyvolume.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipyvolume

extra:
  recipe-maintainers:
    - maartenbreddels
