{% set version = "0.5.0" %}

package:
  name: ipyvolume
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyvolume/ipyvolume-{{ version }}.tar.gz
  sha256: e6fbb81f65b54cc5075a98b10cdabe8513ced06639abc9dacb7749579d25a06a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - traittypes
    - traitlets
    - ipywidgets >=7.4
    - pillow
    - scipy
    - numpy
    - scikit-image >=0.13
    - requests
    - ipywebrtc >=0.4
    - pythreejs >=1.0

test:
  imports:
    - ipyvolume

about:
  home: https://github.com/maartenbreddels/ipyvolume
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'IPython widget for rendering 3d volumes in the Jupter notebook'
  doc_url: https://ipyvolume.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipyvolume

extra:
  recipe-maintainers:
    - maartenbreddels
