{% set name = "ipyvolume" %}
{% set version = "0.5.0" %}
{% set sha256 = "e6fbb81f65b54cc5075a98b10cdabe8513ced06639abc9dacb7749579d25a06a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - traittypes
    - traitlets
    - ipywidgets >=7.0
    - pillow
    - scipy
    - numpy
    - scikit-image >=0.13
    - requests
    - ipywebrtc

test:
  imports:
    - ipyvolume

about:
  home: https://github.com/maartenbreddels/ipyvolume
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'IPython widget for rendering 3d volumes in the Jupter notebook'
  doc_url: https://ipyvolume.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipyvolume

extra:
  recipe-maintainers:
    - maartenbreddels
