{% set version = "0.6.3" %}

package:
  name: ipyvolume
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyvolume/ipyvolume-{{ version }}.tar.gz
  sha256: 823226f90a59ce08b1da2699a9ec505f34f65f01ce43accd80e7d3554082d035

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv . --no-deps --no-build-isolation

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8
    - jupyterlab >=3.0,<4
    - pip
    - python >=3.6
  run:
    - bqplot >=0.12
    - ipyvue >=1.7.0
    - ipyvuetify
    - ipywebrtc >=0.4
    - ipywidgets >=7.0.0
    - matplotlib-base
    - numpy
    - pillow >5.2
    - python >=3.6
    - pythreejs >=2.4.0
    - requests
    - scikit-image >=0.13
    - scipy
    - traitlets
    - traittypes


test:
  imports:
    - ipyvolume
  requires:
    - pip
    - jupyterlab >=3,<4.0
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "ipyvolume.*OK" labextensions

about:
  home: https://github.com/widgetti/ipyvolume
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: IPython widget for rendering 3d volumes
  doc_url: https://ipyvolume.readthedocs.io
  dev_url: https://github.com/widgetti/ipyvolume

extra:
  recipe-maintainers:
    - maartenbreddels
    - bollwyvl
